Feature/emp 15077/send download complete to bookkeper
EricssonBroadcastServices/DevEnigmaRiverAndroidExoPlayerDownload pull request #8
Opened 2020-10-23 12:43 UTC by TordWessman

Aight, so here is the PR for task of sending the request to the backend when a download has complete. (A _lot_ of hazzle for a fairly simple feature.)

Nearly all of the trouble has been related to how the `ISession` (which needs to accompany the metadata for a download request) is seralized/deserialized. 
Due to the fact that we aren't exposing the serialization (BaseJsonSerializable` et. al.), the `Session` and `BusinessUnit` has to implement a their own byte-array serialization using `Parcelable`, but this is in turn not testable.

In the future we should share the serialization logic for everyone in the SDK that needs it and not walk over mountains to accomplish something relatively simple.

2020-10-23 13:21 UTC, MattiasSelinEyevinn requested changes
Se även
https://github.com/EricssonBroadcastServices/DevEnigmaRiverAndroidExoPlayerDownload/pull/9

2020-10-23 13:21 UTC, MattiasSelinEyevinn commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/ExoPlayerDownloadContext.java
> +    static void registerDownloadImplementation(IEnigmaDownloadImplementation downloadImplementation) throws ModuleInitializationException {
Ändra inte :)

2020-10-23 13:21 UTC, MattiasSelinEyevinn commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/BaseJsonSerializable.java
> -
;)

2020-10-23 13:21 UTC, MattiasSelinEyevinn commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/UpdateBookkeeperProcedure.java
> +                    Log.d(TAG, "Download complete failed: " + error.toString());
Kör `error.printStackTrace(TAG)` också

2020-10-23 13:21 UTC, MattiasSelinEyevinn commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/UpdateBookkeeperProcedure.java
> +                }
Generellt undviker vi att spamma loggen när allt gått bra :) 
{Ta bort}/töm onSuccess

2020-10-23 13:24 UTC, Alexander-Atkinson approved these changes

2020-10-23 13:44 UTC, TordWessman commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/BaseJsonSerializable.java
> -
WHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT!!??

2020-10-23 13:47 UTC, TordWessman commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/DownloadedAssetMetaData.java
> +    private static final String SESSION_KEY = "SESSION_KEY";
Det _är_ ju en nyckel till en session i en dictionary och inte en session, men ok.

2020-10-23 13:49 UTC, TordWessman commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/DownloadedAssetMetaData.java
> +            byte []sessionData = serializeParceable(session);
Håller med! typo å mina vägnar

2020-10-23 13:51 UTC, TordWessman commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/UpdateBookkeeperProcedure.java
> +                    Log.d(TAG, "Download complete failed: " + error.toString());
Check!

2020-10-23 13:51 UTC, TordWessman commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/ExoPlayerDownloadContext.java
> +    static void registerDownloadImplementation(IEnigmaDownloadImplementation downloadImplementation) throws ModuleInitializationException {
Har ändrat så mycket fram och tillbaka här att jag omöjligt kan komma ihåg varför jag gjorde den publik...

2020-10-23 13:54 UTC, TordWessman commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/UpdateBookkeeperProcedure.java
> +                }
Låter vettigt. Laborerade fram och tillbaka med vad vi skulle kunna göra av svaret (vi får ju tillbaka en massa info - inte bara nedladdnings-räkningen) och tänkte att det vore vettigt att skriva ut _någon information_.

2020-10-26 08:14 UTC, MattiasSelinEyevinn commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/DownloadedAssetMetaData.java
> +    private static final String SESSION_KEY = "SESSION_KEY";
Jo fast det är ju som att kalla en metod "getNameMethod()" för att det är en metod.

2020-10-26 08:25 UTC, MattiasSelinEyevinn requested changes

2020-10-26 08:25 UTC, MattiasSelinEyevinn commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/UpdateBookkeeperProcedure.java
>                      int count = jsonObject.getInt("downloadCount");
Ta bort det här raden också.

2020-10-26 08:25 UTC, MattiasSelinEyevinn commented on src/main/java/com/redbeemedia/enigma/exoplayerdownload/UpdateBookkeeperProcedure.java
> +                    error.printStackTrace();
Ok. Eller så kan du köra `error.logStackTrace(TAG)`, om du vill. (Sorry, jag skrev error.printStackTrace(TAG) förut, det var fel)

2020-10-26 08:38 UTC, MattiasSelinEyevinn approved these changes

2020-10-26 08:39 UTC, merged